# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: OctopusPack@4
  inputs:
    PackageId: 'testyaml'
    PackageFormat: 'Zip'
    SourcePath: '$(build.ArtifactStagingDirectory)'
- task: OctopusPush@6
  inputs:
    OctoConnectedServiceName: 'test'
    Space: 'Default'
    Packages: '**/*.zip'
    Replace: 'false'
- task: OctopusCreateRelease@6
  inputs:
    OctoConnectedServiceName: 'test'
    Space: 'Default'
    Project: 'dotnetprojectpavanyaml'
- task: OctopusDeployRelease@6
  inputs:
    OctoConnectedServiceName: 'test'
    Space: 'Default'
    Project: 'dotnetprojectpavanyaml'
    ReleaseNumber: '0.0.2'
    Environments: 'Development'



